# Generated by Django 3.0.6 on 2020-05-26 16:16

from django.db import migrations
import datetime
import pandas as pd

def create_data(apps, schema_editor):
    file = "./opencanada/data/34100127.csv"
    df = pd.read_csv(file)

    df = df.drop(df.index[df['GEO'] == 'Census metropolitan areas'].tolist())
    df = df.drop(df.index[df['GEO'] == 'Ottawa-Gatineau, Ontario/Quebec'].tolist())

    ottawa_indices = df.index[df['GEO'] == 'Ottawa-Gatineau, Ontario part, Ontario/Quebec'].tolist()
    gatineau_indices = df.index[df['GEO'] == 'Ottawa-Gatineau, Quebec part, Ontario/Quebec'].tolist()
    for i in ottawa_indices:
        df.loc[i, 'GEO'] = "Ottawa, Ontario"
        
    for i in gatineau_indices:
        df.loc[i, 'GEO'] = "Gatineau, Quebec"

    new = df["GEO"].str.split(", ", n = 1, expand = True) 
    df["CITY"]= new[0] 
    df["PROVINCE"]= new[1]


    Country = apps.get_model('opencanada', 'Country')
    canada = Country(name="Canada")
    canada.save()

    provinces = df.PROVINCE.unique()
    Province = apps.get_model('opencanada', 'Province')
    for p in provinces:
        Province(name=p, country=canada).save()

    city_and_prov = set(zip(df.CITY, df.PROVINCE))
    City = apps.get_model('opencanada', 'City')
    for c, p in city_and_prov:
        prov = Province.objects.filter(name=p)[0]
        City(name=c, province=prov).save()

    VacancyDataSixUnits = apps.get_model('opencanada', 'VacancyDataSixUnits')
    for c, p, r, d in zip(df.CITY, df.PROVINCE, df.VALUE, df.REF_DATE):
        city = City.objects.filter(name=c)[0]
        VacancyDataSixUnits(rate=r, date=datetime.date(d, 1, 1), city = city).save()


class Migration(migrations.Migration):

    dependencies = [
        ('opencanada', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),

    ]
