# Generated by Django 3.0.6 on 2020-06-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencanada', '0003_add_new_housing_price_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingStarts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('housing_starts', models.IntegerField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencanada.Province')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
