# Generated by Django 3.0.6 on 2020-05-26 16:16

from django.db import migrations
import datetime
import pandas as pd

def create_data(apps, schema_editor):
    file = "./opencanada/data/housingstarts.csv"
    df = pd.read_csv(file)

    df.rename(columns={'BritishColumbia': 'British Columbia',
                   'NewBrunswick': 'New Brunswick',
                   'NewfoundlandAndLabrador': 'Newfoundland and Labrador',
                   'NovaScotia': 'Nova Scotia',
                   'PrinceEdwardIsland': 'Prince Edward Island'
                  }, inplace=True)

    df.dropna(subset = ["Ontario"], inplace=True)
    df.drop('Type', axis = 1, inplace=True)
    df.drop('Canada', axis = 1, inplace=True)


    Province = apps.get_model('opencanada', 'Province')
    HousingStarts = apps.get_model('opencanada', 'HousingStarts')


    for index, row in df.iterrows():
        when = row.When.split('/')
        date = datetime.date(int(when[2]), int(when[0]), int(when[1]))
        for col in df.columns:
            if col != 'When':
                prov = Province.objects.filter(name=col)[0]
                HousingStarts(date=date, province=prov, housing_starts=row[col]).save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('opencanada', '0004_housingstarts'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
