FROM node:14.3.0-alpine3.11

ENV REACT_APP_API_URL=http://localhost:80

# RUN addgroup -S frontend && adduser -S frontend -G frontend

WORKDIR /app/frontend

# I dont think I need to copy beacause of volumes
COPY package*.json ./
RUN npm install
COPY src ./src
COPY public ./public

# RUN chown -R frontend:frontend $HOME
# USER frontend
CMD [ "npm", "run", "build"]