version: '3.8'

services:
    web:
        build: ./app
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        expose:
            - 8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_USER=pearse
        - POSTGRES_PASSWORD=p34rse
        - POSTGRES_DB=mydatabase

    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/app/frontend
        ports:
            - "3000:3000"
        stdin_open: true

    
volumes:
    postgres_data:
    # node-modules:
