version: '3.8'

services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        command: gunicorn djangoreactproject.wsgi:application --bind 0.0.0.0:8000
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    nginx:
        build: ./nginx
        volumes:
            - ./frontend/build:/frontend/build
        ports:
            - 80:80
        depends_on:
            - web
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        volumes:
        - ./frontend/build:/app/frontend/build
        stdin_open: true
    
volumes:
    postgres_data: