#pull official base image (python and linux alpine)
FROM certbot/certbot

# WORKDIR /usr/src/app

#install python
# RUN apt-get update -y && apt-get install -y python3.8 python3-pip python3-dev libpq-dev netcat
# # postgresql postgresql-contrib nginx

# RUN pip3 install --upgrade pip


# # copy entrypoint.sh
# COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# #copy project
# COPY . /usr/src/app

# run entrypoint.sh
ENTRYPOINT ["tail", "-f", "/dev/null"]
